export const routerPath = {
  HOME: '',
  LOGIN: 'login',
  SIGNUP: 'signup',
  REGISTER_GRABBZONE: 'register/grabbzone',
  REGISTER_PROJECT: 'register/project',
  PROJECT: 'project',
  PROJECT_DETAIL: 'project/:id',
  GRABB_ZONE: 'grabbzone',
  GRABB_ZONE_DETAIL: 'grabbzone/:id',
  MYPAGE: 'mypage',
  MY_PROFILE: 'profile',
  MY_POSTS: 'posts',
  MY_BOOKMARKS: 'bookmarks',
  MY_PROJECTS: 'projects',
};
