#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

if ! echo "$commit_msg" | grep -qE '^[a-z]+ : [a-z가-힣0-9 ,\-\(\)]+$'; then
  echo "커밋 양식을 지켜주세요"
  exit 1
fi
