import ArrowDownIcon from '@/shared/assets/svg/IcArrowDown.svg?react';
import ArrowUpIcon from '@/shared/assets/svg/IcArrowUp.svg?react';
import LongGithubIcon from '@/shared/assets/svg/IcLongGithub.svg?react';
import ProfileIcon from '@/shared/assets/svg/IcProfile.svg?react';
import ProgrammersIcon from '@/shared/assets/svg/IcProgrammers.svg?react';

export { ArrowDownIcon, ArrowUpIcon, LongGithubIcon, ProgrammersIcon, ProfileIcon };

export { default as IcBookmark } from '@/shared/assets/svg/IcBookmark.svg?react';
export { default as IcChat } from '@/shared/assets/svg/IcChat.svg?react';
export { default as IcChatGithub } from '@/shared/assets/svg/IcChatGithub.svg?react';
export { default as IcChatStart } from '@/shared/assets/svg/IcChatStart.svg?react';
export { default as IcClose } from '@/shared/assets/svg/IcClose.svg?react';
export { default as IcList } from '@/shared/assets/svg/IcList.svg?react';
export { default as IcLoginGithub } from '@/shared/assets/svg/IcLoginGithub.svg?react';
export { default as IcPhoto } from '@/shared/assets/svg/IcPhoto.svg?react';
export { default as IcSend } from '@/shared/assets/svg/IcSend.svg?react';
export { default as IcSendActive } from '@/shared/assets/svg/IcSendActive.svg?react';
export { default as IcDefaultProfile } from '@/shared/assets/svg/IcDefaultProfile.svg?react';
export { default as IcBack } from '@/shared/assets/svg/IcBack.svg?react';
export { default as IcBookmarkSmall } from '@/shared/assets/svg/IcBookmarkSmall.svg?react';
export { default as IcChatSmall } from '@/shared/assets/svg/IcChatSmall.svg?react';
export { default as IcViewSmall } from '@/shared/assets/svg/IcViewSmall.svg?react';
export { default as IcSmallChat } from '@/shared/assets/svg/IcSmallChat.svg?react';
export { default as IcView } from '@/shared/assets/svg/IcView.svg?react';
export { default as IcMinus } from '@/shared/assets/svg/IcMinus.svg?react';
export { default as IcPlus } from '@/shared/assets/svg/IcPlusBig.svg?react';
export { default as IcTrash } from '@/shared/assets/svg/IcTrash.svg?react';
export { default as IcSearch } from '@/shared/assets/svg/IcSearch.svg?react';
export { default as IcCloseSmall } from '@/shared/assets/svg/IcCloseSmall.svg?react';
